Repository ninabrissey/the-film-vault, pull requests merged in 2021-09, with the labels that each got.

#22 Feature/router
  package-lock.json
  package.json
  src/components/App/App.css
  src/components/App/App.js
  src/components/FilmCard/FilmCard.js
  src/components/FilmsContainer/FilmsContainer.css
  src/components/FilmsContainer/FilmsContainer.js
  src/components/MainContent/MainContent.css
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/index.js
Labels: css, javascript, refactor, feature

#25 Feature/proptypes
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/FilmCard/FilmCard.js
  src/components/FilmsContainer/FilmsContainer.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
Labels: enhancement, javascript, feature, error handling

#27 Feature/cypress testing
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/mainpage_spec.js
  cypress/integration/moviepage_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/FilmCard/FilmCard.js
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
Labels: javascript, testing

#29 Feature/search bar
  src/components/IntroHeader/IntroHeader.css
  src/components/IntroHeader/IntroHeader.js
  src/components/MainContent/MainContent.js
  src/components/Nav/Nav.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
Labels: enhancement, javascript

#30 Feature/search bar
  src/components/App/App.js
  src/components/SearchBar/SearchBar.js
Labels: javascript, feature

#31 Feature/page header
  src/components/App/App.css
  src/components/FilmCard/FilmCard.css
  src/components/FilmsContainer/FilmsContainer.css
  src/components/MainContent/MainContent.css
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.css
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/party-title.png
Labels: enhancement, css, feature

#32 Feature/loading page
  public/favicon.ico
  src/components/Loading/Loading.css
  src/components/Loading/Loading.js
  src/components/MainContent/MainContent.js
  src/loadingLogo.png
  src/logo.png
Labels: javascript, feature

#33 Refactor/refactor search
  public/index.html
  src/components/App/App.js
  src/components/FilmCard/FilmCard.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/SearchBar/SearchBar.js
Labels: enhancement, javascript, refactor, error handling

#34 Refactor/refactor main page css
  src/components/App/App.js
  src/components/FilmCard/FilmCard.css
  src/components/MainContent/MainContent.css
  src/components/Nav/Nav.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
Labels: enhancement, css, refactor

#35 Feature/not found component
  src/components/App/App.css
  src/components/App/App.js
  src/components/MainContent/MainContent.css
  src/components/Nav/Nav.css
  src/components/NotFound/NotFound.css
  src/components/NotFound/NotFound.js
  src/components/SearchBar/SearchBar.css
  src/notFoundLogo.png
Labels: enhancement, css, javascript, feature, error handling

#36 Feature/style individual page
  src/components/FilmCard/FilmCard.css
  src/components/FilmCard/FilmCard.js
  src/components/Movie/Movie.css
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
Labels: css

#38 Feature/cypress testing
  cypress/integration/mainpage_spec.js
  cypress/integration/moviepage_spec.js
  cypress/integration/notfound_spec.js
  cypress/integration/search_spec.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: javascript, testing

#39 Feature/movie page styling
  public/favicon2.ico
  public/favicon3.ico
  public/index.html
  src/components/FilmCard/FilmCard.css
  src/components/FilmCard/FilmCard.js
  src/components/MainContent/MainContent.css
  src/components/Movie/Movie.css
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/components/SearchBar/SearchBar.js
Labels: enhancement, css, javascript, error handling

#40 Feature/refactor
  cypress/support/commands.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/components/FilmCard/FilmCard.js
  src/components/Loading/Loading.css
  src/components/Loading/Loading.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/index.js
  src/logo.svg
Labels: css, javascript, refactor

#41 Feature/scroll to top
  src/components/App/App.js
  src/components/SearchBar/SearchBar.js
Labels: feature
