Repository ninabrissey/the-film-vault, pull requests merged in 2021-08, with the labels that each got.

#10 Feature/display single movie
  src/components/App/App.js
  src/components/FilmsContainer/FilmsContainer.css
  src/components/FilmsContainer/FilmsContainer.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.css
  src/components/Movie/Movie.js
Labels: css, javascript, feature

#11 Feature/individual movie display
  package-lock.json
  package.json
  public/index.html
  src/components/App/App.css
  src/components/App/App.js
  src/components/FilmCard/FilmCard.js
  src/components/FilmsContainer/FilmsContainer.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
  src/index.js
Labels: css, javascript, feature

#12 Feature/nav component
  package-lock.json
  src/components/App/App.css
  src/components/App/App.js
  src/components/FilmsContainer/FilmsContainer.js
  src/components/MainContent/MainContent.css
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.css
  src/components/Movie/Movie.js
  src/components/Nav/Nav.css
  src/components/Nav/Nav.js
  src/logo.png
Labels: question, javascript, refactor, feature

#18 Feature/error handling
  src/apiCalls.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
Labels: javascript, feature, error handling

#20 Feature/format movie details
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/FilmCard/FilmCard.js
  src/components/FilmsContainer/FilmsContainer.js
  src/components/MainContent/MainContent.js
  src/components/Movie/Movie.js
Labels: javascript, feature
